### ISSUE TITLE
Failed to connect to MySQL

### ISSUE THREAD

**Issue by kang28ivan** [ismaelyws/themely#1]
I try first time install its not working.

`Failed to connect to MySQL: Can't connect to MySQL server on 'themely.ce2w7jtoslva.us-east-1.rds.amazonaws.com' (111)`

https://prnt.sc/qcw2vv

**Comment by ismaelyws** [comment]
Hello @kang28ivan 

I was able to replicate the issue on my end. You must add port 3306 to outgoing TCP ports
 in your firewall settings.

_WHM->ConfigServer Firewall->Firewall Configuration->All Outgoing TCP Ports, add 3306_

Let me know if you encounter any other issues.

**Comment by kang28ivan** [comment]
Ok fixed, case closed! 
No plan for directadmin plugins? 
this beautiful plugins and many thanks for this great plugin

**Comment by ismaelyws** [comment]
Yes, I do plan on building a plugin for DirectAdmin.

I am not sure exactly when but I will notify you once I do.

I'm glad you like it :) 

If you have any suggestions on how I can make it better, please let me know.

**Comment by ismaelyws** [comment]
@kang28ivan also, may I ask what is the name of your hosting company?

**Comment by kang28ivan** [comment]
I'am based in Indonesia hosting company name "Warna Hosting"

**Comment by kang28ivan** [comment]
I installed this plugins because I got notification on my email about this plugins, so I just try install on my one cpanel servers.

**Comment by ismaelyws** [comment]
@kang28ivan well I am glad you did, thank you :)

I am working on some new features this week and I will release an update in a few days.

Once I do I will notify you so you can update the plugin.

**Comment by kang28ivan** [comment]
OK, thank you very much
and hopefully get good feedback from my clients about this plugin

**Comment by ismaelyws** [comment]
Whatever the feedback is, I am interested to know. This way I can improve it. Thank you again and have a great day :)

**Comment by ismaelyws** [comment]
@kang28ivan I have sent you an email with details about the update I just released.

**Comment by kang28ivan** [comment]
> @kang28ivan I have sent you an email with details about the update I just released.

Thank your for update ^_^
Already update, but I got error when activate server https://prnt.sc/qicio5

**Comment by ismaelyws** [comment]
@kang28ivan hmm, ok. Let me debug this issue and get back to you. 

Can you send me a dump of your error_log? 

Error Log Path: /usr/local/cpanel/logs/error_log

**Comment by kang28ivan** [comment]
> @kang28ivan hmm, ok. Let me debug this issue and get back to you.
> 
> Can you send me a dump of your error_log?
> 
> Error Log Path: /usr/local/cpanel/logs/error_log

Here the error_log

`[2020-01-02 12:21:55 +0700] info [install_plugin] Installing to paper_lantern
[2020-01-02 12:21:55 +0700] info [install_plugin] Installing themely in Feature Manager ...
[2020-01-02 12:21:55 +0700] info [install_plugin] Done
[2020-01-02 12:21:55 +0700] info [install_plugin] Scheduling task to update sprites
[2020-01-02 12:21:55 +0700] info [install_plugin] Scheduling task to update API spec files
[2020-01-02 12:21:55 +0700] info [cpsrvd] reloading config based on -HUP signal
[2020-01-02 12:21:57 +0700] info [register_appconfig] appconfig::Notify Notification => kang28ivan@gmai***** via EMAIL [eventimportance => Low (3)]
[2020-01-02 12:21:58 +0700] warn [queueprocd] Failed to fetch cPStore products list: Cpanel::Exception::cPStoreError/(XID xsv5jn) The [asis,cPanel Store] returned an error (X::UnlicensedIP) in response to the request “GET products/cpanel/4?version=11.84.0”: The remote ip address, 103.28.23.82, is not licensed.
 at /usr/local/cpanel/Cpanel/cPStore.pm line 240.
	Cpanel::cPStore::__ANON__(Cpanel::Exception::HTTP::Server=HASH(0x2aac3a0)) called at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Try/Tiny.pm line 118
	Try::Tiny::try(CODE(0x251b128), Try::Tiny::Catch=REF(0x16e64e8)) called at /usr/local/cpanel/Cpanel/cPStore.pm line 248
	Cpanel::cPStore::_request(Cpanel::cPStore=HASH(0x22a20b8), "get", "products/cpanel/4?version=11.84.0") called at /usr/local/cpanel/Cpanel/cPStore.pm line 196
	Cpanel::cPStore::get(Cpanel::cPStore=HASH(0x22a20b8), "products/cpanel/4?version=11.84.0") called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore/ProductsCache.pm line 66
	Cpanel::Market::Provider::cPStore::ProductsCache::_fetch_from_cpstore() called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore/ProductsCache.pm line 78
	Cpanel::Market::Provider::cPStore::ProductsCache::__ANON__() called at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Try/Tiny.pm line 97
	eval {...} called at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Try/Tiny.pm line 88
	Try::Tiny::try(CODE(0x266a5b0), Try::Tiny::Catch=REF(0x256ac78)) called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore/ProductsCache.pm line 96
	Cpanel::Market::Provider::cPStore::ProductsCache::_LOAD_FRESH("Cpanel::Market::Provider::cPStore::ProductsCache") called at /usr/local/cpanel/Cpanel/CacheFile.pm line 226
	Cpanel::CacheFile::load("Cpanel::Market::Provider::cPStore::ProductsCache") called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore/ProductsCache.pm line 139
	Cpanel::Market::Provider::cPStore::ProductsCache::load_with_short_name("Cpanel::Market::Provider::cPStore::ProductsCache") called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore/ProductsCache.pm line 104
	Cpanel::Market::Provider::cPStore::ProductsCache::load("Cpanel::Market::Provider::cPStore::ProductsCache") called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore.pm line 147
	Cpanel::Market::Provider::cPStore::_get_products_list_for_validation() called at /usr/local/cpanel/Cpanel/Market/Provider/cPStore.pm line 134
	Cpanel::Market::Provider::cPStore::get_products_list() called at /usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/Market/META.pm line 117
	Cpanel::Config::ConfigObj::Driver::Market::META::__ANON__() called at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Try/Tiny.pm line 97
	eval {...} called at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Try/Tiny.pm line 88
	Try::Tiny::try(CODE(0x2669f68), Try::Tiny::Catch=REF(0x209f960)) called at /usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/Market/META.pm line 122
	Cpanel::Config::ConfigObj::Driver::Market::META::can_be_enabled() called at /usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/Market/META.pm line 146
	Cpanel::Config::ConfigObj::Driver::Market::META::auto_enable("Cpanel::Config::ConfigObj::Driver::Market::META") called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 105
	Cpanel::Config::ConfigObj::_unload_if_auto_enabled("Cpanel::Config::ConfigObj::Driver::Market", "Cpanel::Config::ConfigObj::Driver::Market::META") called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 159
	Cpanel::Config::ConfigObj::get_available_drivers(undef, 0, 0) called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 568
	Cpanel::Config::ConfigObj::_get_drivers(Cpanel::Config::ConfigObj=HASH(0x1fac778)) called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 712
	Cpanel::Config::ConfigObj::call_all(Cpanel::Config::ConfigObj=HASH(0x1fac778), "acl_desc") called at /usr/local/cpanel/Whostmgr/ACLS.pm line 100
	Whostmgr::ACLS::_dynamic_acl_items() called at /usr/local/cpanel/Whostmgr/ACLS.pm line 121
	Whostmgr::ACLS::_get_dynamic_acl_lists() called at /usr/local/cpanel/Whostmgr/ACLS.pm line 168
	Whostmgr::ACLS::_dynamic_acl_update() called at /usr/local/cpanel/Whostmgr/ACLS.pm line 105
	Whostmgr::ACLS::get_dynamic_acl_lists() called at /usr/local/cpanel/Whostmgr/Templates/Chrome/Resellers.pm line 90
	Whostmgr::Templates::Chrome::Resellers::process_all_resellers() called at /usr/local/cpanel/scripts/rebuild_whm_chrome line 49
	scripts::rebuild_whm_chrome::run() called at /usr/local/cpanel/Cpanel/TaskProcessors/WHMChromeTasks.pm line 33
	Cpanel::TaskProcessors::WHMChromeTasks::Rebuild::_do_child_task(Cpanel::TaskProcessors::WHMChromeTasks::Rebuild=HASH(0xb3aaa8), Cpanel::TaskQueue::Task=HASH(0x1846a18), Cpanel::LoggerAdapter=HASH(0xb170c0)) called at /usr/local/cpanel/Cpanel/TaskQueue/ChildProcessor.pm line 68
	eval {...} called at /usr/local/cpanel/Cpanel/TaskQueue/ChildProcessor.pm line 71
	Cpanel::TaskQueue::ChildProcessor::process_task(Cpanel::TaskProcessors::WHMChromeTasks::Rebuild=HASH(0xb3aaa8), Cpanel::TaskQueue::Task=HASH(0x1846a18), Cpanel::LoggerAdapter=HASH(0xb170c0), Cpanel::StateFile::Guard=HASH(0x17b6018)) called at /usr/local/cpanel/Cpanel/TaskQueue/FastSpawn.pm line 24
	Cpanel::TaskQueue::FastSpawn::process_task(Cpanel::TaskProcessors::WHMChromeTasks::Rebuild=HASH(0xb3aaa8), Cpanel::TaskQueue::Task=HASH(0x1846a18), Cpanel::LoggerAdapter=HASH(0xb170c0), Cpanel::StateFile::Guard=HASH(0x17b6018)) called at /usr/local/cpanel/Cpanel/TaskQueue.pm line 619
	eval {...} called at /usr/local/cpanel/Cpanel/TaskQueue.pm line 619
	Cpanel::TaskQueue::process_next_task(Cpanel::TaskQueue=HASH(0x1665908)) called at /usr/local/cpanel/Cpanel/QueueProcd/Queueing.pm line 49
	eval {...} called at /usr/local/cpanel/Cpanel/QueueProcd/Queueing.pm line 49
	Cpanel::QueueProcd::Queueing::queue_process_next_task(Cpanel::TaskQueue=HASH(0x1665908), Cpanel::LoggerAdapter=HASH(0xb170c0)) called at libexec/queueprocd.pl line 473
	libexec::queueprocd::process_tasks(Cpanel::TaskQueue=HASH(0x1665908), Cpanel::TaskQueue::Scheduler=HASH(0x166e9a8)) called at libexec/queueprocd.pl line 490
	libexec::queueprocd::_process_tasks_until_no_more_are_ready(Cpanel::TaskQueue=HASH(0x1665908), Cpanel::TaskQueue::Scheduler=HASH(0x166e9a8)) called at libexec/queueprocd.pl line 223
	libexec::queueprocd::script("libexec::queueprocd", "--reexec") called at libexec/queueprocd.pl line 126
 at /usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/Market/META.pm line 121.
	Cpanel::Config::ConfigObj::Driver::Market::META::__ANON__(Cpanel::Exception::cPStoreError=HASH(0x2aac280)) called at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Try/Tiny.pm line 118
	Try::Tiny::try(CODE(0x2669f68), Try::Tiny::Catch=REF(0x209f960)) called at /usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/Market/META.pm line 122
	Cpanel::Config::ConfigObj::Driver::Market::META::can_be_enabled() called at /usr/local/cpanel/Cpanel/Config/ConfigObj/Driver/Market/META.pm line 146
	Cpanel::Config::ConfigObj::Driver::Market::META::auto_enable("Cpanel::Config::ConfigObj::Driver::Market::META") called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 105
	Cpanel::Config::ConfigObj::_unload_if_auto_enabled("Cpanel::Config::ConfigObj::Driver::Market", "Cpanel::Config::ConfigObj::Driver::Market::META") called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 159
	Cpanel::Config::ConfigObj::get_available_drivers(undef, 0, 0) called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 568
	Cpanel::Config::ConfigObj::_get_drivers(Cpanel::Config::ConfigObj=HASH(0x1fac778)) called at /usr/local/cpanel/Cpanel/Config/ConfigObj.pm line 712
	Cpanel::Config::ConfigObj::call_all(Cpanel::Config::ConfigObj=HASH(0x1fac778), "acl_desc") called at /usr/local/cpanel/Whostmgr/ACLS.pm line 100
	Whostmgr::ACLS::_dynamic_acl_items() called at /usr/local/cpanel/Whostmgr/ACLS.pm line 121
	Whostmgr::ACLS::_get_dynamic_acl_lists() called at /usr/local/cpanel/Whostmgr/ACLS.pm line 168
	Whostmgr::ACLS::_dynamic_acl_update() called at /usr/local/cpanel/Whostmgr/ACLS.pm line 105
	Whostmgr::ACLS::get_dynamic_acl_lists() called at /usr/local/cpanel/Whostmgr/Templates/Chrome/Resellers.pm line 90
	Whostmgr::Templates::Chrome::Resellers::process_all_resellers() called at /usr/local/cpanel/scripts/rebuild_whm_chrome line 49
	scripts::rebuild_whm_chrome::run() called at /usr/local/cpanel/Cpanel/TaskProcessors/WHMChromeTasks.pm line 33
	Cpanel::TaskProcessors::WHMChromeTasks::Rebuild::_do_child_task(Cpanel::TaskProcessors::WHMChromeTasks::Rebuild=HASH(0xb3aaa8), Cpanel::TaskQueue::Task=HASH(0x1846a18), Cpanel::LoggerAdapter=HASH(0xb170c0)) called at /usr/local/cpanel/Cpanel/TaskQueue/ChildProcessor.pm line 68
	eval {...} called at /usr/local/cpanel/Cpanel/TaskQueue/ChildProcessor.pm line 71
	Cpanel::TaskQueue::ChildProcessor::process_task(Cpanel::TaskProcessors::WHMChromeTasks::Rebuild=HASH(0xb3aaa8), Cpanel::TaskQueue::Task=HASH(0x1846a18), Cpanel::LoggerAdapter=HASH(0xb170c0), Cpanel::StateFile::Guard=HASH(0x17b6018)) called at /usr/local/cpanel/Cpanel/TaskQueue/FastSpawn.pm line 24
	Cpanel::TaskQueue::FastSpawn::process_task(Cpanel::TaskProcessors::WHMChromeTasks::Rebuild=HASH(0xb3aaa8), Cpanel::TaskQueue::Task=HASH(0x1846a18), Cpanel::LoggerAdapter=HASH(0xb170c0), Cpanel::StateFile::Guard=HASH(0x17b6018)) called at /usr/local/cpanel/Cpanel/TaskQueue.pm line 619
	eval {...} called at /usr/local/cpanel/Cpanel/TaskQueue.pm line 619
	Cpanel::TaskQueue::process_next_task(Cpanel::TaskQueue=HASH(0x1665908)) called at /usr/local/cpanel/Cpanel/QueueProcd/Queueing.pm line 49
	eval {...} called at /usr/local/cpanel/Cpanel/QueueProcd/Queueing.pm line 49
	Cpanel::QueueProcd::Queueing::queue_process_next_task(Cpanel::TaskQueue=HASH(0x1665908), Cpanel::LoggerAdapter=HASH(0xb170c0)) called at libexec/queueprocd.pl line 473
	libexec::queueprocd::process_tasks(Cpanel::TaskQueue=HASH(0x1665908), Cpanel::TaskQueue::Scheduler=HASH(0x166e9a8)) called at libexec/queueprocd.pl line 490
	libexec::queueprocd::_process_tasks_until_no_more_are_ready(Cpanel::TaskQueue=HASH(0x1665908), Cpanel::TaskQueue::Scheduler=HASH(0x166e9a8)) called at libexec/queueprocd.pl line 223
	libexec::queueprocd::script("libexec::queueprocd", "--reexec") called at libexec/queueprocd.pl line 126
[2020-01-02 12:22:02 +0700] info [whostmgrd] Successfully verified signature for cpanel (key types: release).
[2020-01-02 12:22:23 +0700] warn [whostmgrd] The subprocess (php) exited with an error: The subprocess reported error number 1 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 251.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2146e08)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 109
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2146e08), "subprocess_name", "php", "subprocess_pid_to_reap", 3531309, "subprocess_read_handle", GLOB(0x2147138), "subprocess_write_handle", ...) called at cpsrvd.pl line 7138
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6912
	cpanel::cpsrvd::phpHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6569
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1972
	cpanel::cpsrvd::dodoc(HASH(0x139ff08)) called at cpsrvd.pl line 1717
	cpanel::cpsrvd::handle_one_connection(6) called at cpsrvd.pl line 1097
	cpanel::cpsrvd::script() called at cpsrvd.pl line 425
[2020-01-02 12:24:16 +0700] warn [whostmgrd] The subprocess (php) exited with an error: The subprocess reported error number 1 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 251.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x21c9dc8)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 109
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x21c9dc8), "subprocess_name", "php", "subprocess_pid_to_reap", 3533604, "subprocess_read_handle", GLOB(0x2092c98), "subprocess_write_handle", ...) called at cpsrvd.pl line 7138
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6912
	cpanel::cpsrvd::phpHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6569
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1972
	cpanel::cpsrvd::dodoc(HASH(0x139ff08)) called at cpsrvd.pl line 1717
	cpanel::cpsrvd::handle_one_connection(6) called at cpsrvd.pl line 1097
	cpanel::cpsrvd::script() called at cpsrvd.pl line 425
[2020-01-02 12:27:18 +0700] warn [whostmgrd] The subprocess (php) exited with an error: The subprocess reported error number 1 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 251.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x21c3c48)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 109
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x21c3c48), "subprocess_name", "php", "subprocess_pid_to_reap", 3538068, "subprocess_read_handle", GLOB(0x1fcdca8), "subprocess_write_handle", ...) called at cpsrvd.pl line 7138
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6912
	cpanel::cpsrvd::phpHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6569
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1972
	cpanel::cpsrvd::dodoc(HASH(0x139ff08)) called at cpsrvd.pl line 1717
	cpanel::cpsrvd::handle_one_connection(6) called at cpsrvd.pl line 1097
	cpanel::cpsrvd::script() called at cpsrvd.pl line 425`

**Comment by ismaelyws** [comment]
Thank you.

Ok, so it doesn't look like it's a server error. Let me try and replicate the issue on my end and get back to you.

Thanks for your patience :)

**Comment by ismaelyws** [comment]
@kang28ivan Also, can you send me a screenshot of your screen when in WHM > Plugins > Themely? Does it display the number of Active Accounts in the Server Information panel?

**Comment by kang28ivan** [comment]
> @kang28ivan Also, can you send me a screenshot of your screen when in WHM > Plugins > Themely? Does it display the number of Active Accounts in the Server Information panel?

Not shown on active account https://prnt.sc/qicq19

**Comment by ismaelyws** [comment]
@kang28ivan ok, that helps. Now I know where to start looking. It's not able to get the number of active accounts so it returns a NULL value which is what causes the error message when you tried to activate the server. I will debug and get back to you.

**Comment by ismaelyws** [comment]
@kang28ivan Quick question -  does your server have a SSL certificate installed? When you log into WHM is it secured (https)?

**Comment by kang28ivan** [comment]
> @kang28ivan Quick question - does your server have a SSL certificate installed? When you log into WHM is it secured (https)?

Yes I have & installed on hostname

**Comment by ismaelyws** [comment]
@kang28ivan Ok, that helps me narrow it down. Thank you.

**Comment by ismaelyws** [comment]
@kang28ivan Ok, I think I know what the issue is. I am working on a fix and will release an update tomorrow.

**Comment by ismaelyws** [comment]
@kang28ivan thank you for your patience. I have released an update which should fix the issue. I have switched from user/password authentication for WHM API calls to token based authentication.

Follow the update instructions https://github.com/ismaelyws/themely#update-instructions and Step 2 of the installation instructions https://github.com/ismaelyws/themely#step-2

Please let me know if you encounter any issues.

**Comment by kang28ivan** [comment]
> @kang28ivan thank you for your patience. I have released an update which will fix the issue.
> 
> Follow the update instructions https://github.com/ismaelyws/themely#update-instructions and Step 2 of the installation instructions https://github.com/ismaelyws/themely#step-2
> 
> Please let me know if you encounter any issues.

Working now, I just wan;t to ask, how to edit user information? I think my paypal email incorrect

**Comment by ismaelyws** [comment]
@kang28ivan Ah, great, glad to hear it working :)

Please send me an email to ismaelyws@gmail.com with the correct PayPal email and I will change in our system.

**Comment by kang28ivan** [comment]
Hi @ismaelyws I have problem when install on new server, problem like this https://prnt.sc/qzzeet
I already reinstall but still same

**Comment by ismaelyws** [comment]
@kang28ivan that's very strange :|

It seems like cPanel is not loading the header which loads the stylesheet for the paperlantern theme.

Is this on a newly setup server?

**Comment by kang28ivan** [comment]
> @kang28ivan that's very strange :|
> 
> It seems like cPanel is not loading the header which loads the stylesheet for the paperlantern theme.
> 
> Is this on a newly setup server?

Yes its new setup server, but another plugins working no issue

**Comment by ismaelyws** [comment]
@kang28ivan and this only occurs on the WHM dashboard?

Does this server run CentOS, CloudLinux or RHEL?

**Comment by kang28ivan** [comment]
Only happens in themely plugins, dashboards with no problems
Yes, I run Cloudlinux 7

**Comment by ismaelyws** [comment]
The plugin loads the WHM header from /usr/local/cpanel/php/WHM.php

Can you tell me if the WHM.php file is located in another folder on that server?

**Comment by kang28ivan** [comment]
The location of whm.php is correct exactly as you mentioned https://prnt.sc/r0b4jj

**Comment by ismaelyws** [comment]
Ok, let me look into this further. I'll get back to you ASAP.

**Comment by ismaelyws** [comment]
@kang28ivan can you take a screenshot of the Elements and Console tabs in your Developer Tools? Example screenshot 
![image](https://user-images.githubusercontent.com/8916526/74173958-12a98800-4c01-11ea-9962-696b74867c7e.png)

**Comment by kang28ivan** [comment]
Here https://prnt.sc/r0bn16 in console tab nothing https://prnt.sc/r0bodh

**Comment by ismaelyws** [comment]
You have to be on the Themely WHM dashboard page, then open developer tools and then take the screenshot.

**Comment by kang28ivan** [comment]
https://prnt.sc/r0bsw6 in console tab nothing

**Comment by ismaelyws** [comment]
@kang28ivan ok, can you take a screenshot of the Network tab in the developer tools? 
![image](https://user-images.githubusercontent.com/8916526/74176944-b8abc100-4c06-11ea-9c1a-3665570c3b7b.png)

**Comment by kang28ivan** [comment]
Also when I try on another server reinstall can't be add again the license x_x
because the license was previously inactive so I reinstall and input license + API Token
![Screenshot_6](https://user-images.githubusercontent.com/53988458/74177009-d105f500-4c73-11ea-92e9-567f4962b579.png)

![Screenshot_5](https://user-images.githubusercontent.com/53988458/74176904-969c5800-4c73-11ea-9439-3cc4352b5c82.png)

**Comment by kang28ivan** [comment]
> @kang28ivan ok, can you take a screenshot of the Network tab in the developer tools?
> ![image](https://user-images.githubusercontent.com/8916526/74176944-b8abc100-4c06-11ea-9c1a-3665570c3b7b.png)

Here the result https://prnt.sc/r0c0od

**Comment by ismaelyws** [comment]
@kang28ivan if you uninstall you should first deactivate the server (click red button), then uninstall. Otherwise it will think you are trying to activate a server which is already activated, that is why you get error "has already been taken".

**Comment by kang28ivan** [comment]
> @kang28ivan if you uninstall you should first deactivate the server (click red button), then uninstall. Otherwise it will think you are trying to activate a server which is already activated, that is why you get error "has already been taken".

I already click reds button before, but not working and also I forgot screenshot error message

**Comment by ismaelyws** [comment]
Ok, I manually deactivated this server, now you can re-install and activate 
![image](https://user-images.githubusercontent.com/8916526/74177625-1ee51380-4c08-11ea-85a9-966bfe308c63.png)

**Comment by kang28ivan** [comment]
> Ok, I manually deactivated this server, now you can re-install and activate
> ![image](https://user-images.githubusercontent.com/8916526/74177625-1ee51380-4c08-11ea-85a9-966bfe308c63.png)

Ok thank you, also can you deactivate on baduy server?

**Comment by ismaelyws** [comment]
Ok, I deactivated baduy server.

**Comment by kang28ivan** [comment]
This already active but nobut the display still does not contain headers and footers and css
Previously I already installed on this server but for some reason a few days later it looks like that
![Screenshot_7](https://user-images.githubusercontent.com/53988458/74178304-4a064c00-4c76-11ea-9824-0ea298d3d83d.png)

**Comment by ismaelyws** [comment]
Now this is happening on all servers? not just the new one?

**Comment by kang28ivan** [comment]
> Now this is happening on all servers? not just the new one?
No, just one server. I do not understand what is happening on this server, but I make sure there are no problems in cpanel
Then on end user cpanel its working not crash like on WHM.
A few weeks ago I also received praise from more than six customers, but I forgot to do a screenshot because in a private conversation, one of them through facebook messenger.
https://prnt.sc/r0cagg he said "the wordpress installer is amazing" and automatically installed from my whmcs, I use the default random theme option on the whmcs hook

**Comment by ismaelyws** [comment]
> No, just one server. I do not understand what is happening on this server, but I make sure there are no problems in cpanel
That is so weird. If this is a new server, would you mind giving me access so I can log in to WHM and try to solve the issue? I understand if you are not comfortable with that. You can of course change the password after. Other option I see is you send me the error log located in /usr/local/cpanel/logs/error_log.

> he said "the wordpress installer is amazing" and automatically installed from my whmcs, I use the default random theme option on the whmcs hook
:) that's great! Very happy to hear that!

**Comment by ismaelyws** [comment]
You should see this in Network tab 
![image](https://user-images.githubusercontent.com/8916526/74179563-b39d4080-4c0b-11ea-945a-81f1e31f301f.png)

**Comment by kang28ivan** [comment]
> That is so weird. If this is a new server, would you mind giving me access so I can log in to WHM and try to solve the issue? I understand if you are not comfortable with that. You can of course change the password after. Other option I see is you send me the error log located in /usr/local/cpanel/logs/error_log. 

I will give it to you later, because I use the same password on all my servers x_x
while this is not a problem for display on WHM, most importantly the server can be connected to the license and from the cpanel side it still runs normally

> :) that's great! Very happy to hear that!

Yes, I hope users are happy and do not need many more clicks to access Softaculous.

for now I hope to come to the directadmin plugin, because I have more directadmin users than cpanel users, many have been interested in DirectAdmin that they didn't know about previously. It's better if I can sell cheaper hosting under cpanel

**Comment by ismaelyws** [comment]
Yes, what is most important is that the cPanel side is working.

If you send me the error log hopefully I can find the problem and maybe I won't need to log into WHM.

Eventually we will build a plugin for DirectAdmin.

**Comment by ismaelyws** [comment]
@kang28ivan We released an update on Monday with some improvements. Can you install the update on the server that had issues with the WHM dashboard? In your case you will need to uninstall then re-install the plugin https://plugin.themely.com/#update (make sure to deactivate the server first).

**Comment by kang28ivan** [comment]
Hi, I already remove and install but now have error message like this "**The requested machine 'baduy.securewhnetwork.com' was not found**"
![Screenshot_1](https://user-images.githubusercontent.com/53988458/75114559-e62a4d00-5691-11ea-8c36-43265b4c5669.png)

**Comment by kang28ivan** [comment]
Sorry I corrected, this is working now after being reinstalled
![Screenshot_2](https://user-images.githubusercontent.com/53988458/75114615-841e1780-5692-11ea-8088-baef83db722b.png)

**Comment by ismaelyws** [comment]
@kang28ivan excellent, glad to hear it's fixed.

**Comment by ismaelyws** [comment]
@kang28ivan I sent you an email about your earnings but never received a response. What's the best way to contact you?
